### PR TITLE
Adds core infrastructure

### PR DESCRIPTION
**Pull request by cesar-rodriguez**
This PR:

- Includes a docker-compose file that will have the application use a postgresql database instead of a local sqlite 
- Includes core terraform components necessary to provision the application in AWS except the HELM chart which will be generated by appCD

### CODE REVIEW

**Comment by cesar-rodriguez** [comment]
atlantis apply

**Comment by cesar-rodriguez** [comment]
atlantis plan

**Comment by cesar-rodriguez** [comment]
atlantis help

**Comment by cesar-rodriguez** [comment]
atlantis plan -d infrastructure/core/eks

**Comment by cesar-rodriguez** [comment]
atlantis plan

**Comment by cesar-rodriguez** [comment]
atlantis plan --help

**Comment by cesar-rodriguez** [comment]
atlantis apply

**Comment by cesar-rodriguez** [comment]
atlantis plan

**Review by iacgen — APPROVED** [review]

**Pull request merged**
